version: "3"

services:
  app:
    image: climate-cockpit:latest
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
      - ./media-files:/media-files
      - ./static-files:/static-files
    command: "sh /scripts/dev.sh"
    env_file:
      - ./envs/dev.env
    depends_on:
      - postgres

  postgres:
    image: postgres:16.0
    ports:
      - "5432:5432"
    env_file:
      - ./envs/dev.env
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db:
